### ISSUE TITLE
Rendering Issues

### ISSUE THREAD

**Issue by ahmed-alamer** [aragalie/solarized-dark-unified#1] opened 2023-09-18 18:05 UTC
# Description
Rendering keeps breaking and the editor will become unusable.

# Steps to Reproduce
+ Install the plugin
+ Just open any editor, try invoke auto complete, or scroll, or just switch to another editor tab and back

# Screenshot
Notice that I have switch away from the json file to a Java file, and that selection was sticky even after I clicked away.

![image](https://github.com/aragalie/solarized-dark-unified/assets/7933802/9821813b-33f3-47b1-a39b-c4d6c83eaddd)

# Environment Information
IntelliJ IDEA Ultimate 2023.2.2
Windows 10 Pro
27" 4K monitor

**Comment by aragalie** [comment] 2023-09-18 18:22
I have IDEA Ultimate as well, and nothing like this occurs on my end...did you try restarting?

Also, did you enable as well the Editor theme separately?

**Comment by aragalie** [comment] 2023-09-18 18:27
Additionally, can you please install also the theme "Solarized Dark" by Tyler Thrailkill and check if you get the same behavior?

My theme is based on that one as well.

**Comment by ahmed-alamer** [comment] 2023-09-18 18:43
I am on IntelliJ IDEA Ultimate 2023.2.2

"Solarized Dark" by Tyler Thrailkill has no issues, do I need to install it side-by-side, meaning install "Solarized Dark" by Tyler Thrailkill then the unified theme?

**Comment by aragalie** [comment] 2023-09-18 19:30
They are completely separate themes, I just wanted to understand if there is a deeper issue, as they are both very similar (mine is based on his).

**Comment by ahmed-alamer** [comment] 2023-09-18 19:35
I will tell you one thing, I have the issue on two separate computers, and the common theme is that both are connected to 4K displays.

**Comment by aragalie** [comment] 2023-09-19 06:07
Nothing should be resolution-dependent, so my guess is that the issue is related to your setup. Can't reproduce this in any way on my end unfortunately, even on high-res screens.

**Comment by ahmed-alamer** [comment] 2023-09-19 13:04
are you on Windows or Mac?

**Comment by aragalie** [comment] 2023-09-19 13:35
Mac.

Btw, I've pushed a few updates, let's see if anything changes for you.

**Comment by ahmed-alamer** [comment] 2023-09-19 13:43
I am on Windows. Will do thank you, do I have to install manually or it's published on the marketplace

**Comment by aragalie** [comment] 2023-09-19 14:15
It's on the marketplace, you'll get an automatic notification to update it in Plugins.

**Comment by ahmed-alamer** [comment] 2023-09-19 15:41
No dice, same issue. I am pretty certain it has to do with Windows 10, I am gonna try it on my Windows 11 box. I noticed one thing, when the plugin is installed it uses the Classic Light color scheme for some reason

**Comment by aragalie** [comment] 2023-09-19 17:11
The Classic Light is an issue I'll fix at some point, happens to me as well, but not sure yet what's the problem. That's why for now in the instructions it says to manually select the theme also in Editor Color Scheme, after installing it.

**Comment by aragalie** [comment] 2023-10-26 09:22
@ahmed-alamer pushed another bugfix now, please try it and let me know (version `1.09`)

**Comment by aragalie** [comment] 2023-11-07 07:14
Closing this issue as I can't reproduce it and it doesn't seem to be related to the theme plugin itself.

**Closed as completed by aragalie** 2023-11-07 07:14 UTC
